name: Scrape *info about data goes here*

on:
  push:
  workflow_dispatch:
  schedule:
  # uncomment this when deploying
    # - cron: "4,24,44 * * * *"

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
      - name: Check out this repo
        uses: actions/checkout@v3
      - name: Fetch latest data
        run: |-
          # curl */scraped_data_url*/ | jq '.'  > output_file.json
      - name: Commit and push if changed
        run: |-
          git config user.name "Automated"
          git config user.email "actions@users.noreply.github.com"
          git add -A
          timestamp=$(date -u)
          git commit -m "Latest data: ${timestamp}" || exit 0
          git push