name: Scrape DNRC Fire Data

on:
  push:
  workflow_dispatch:
  schedule:
  # - cron: "4,24,44 * * * *"

  - cron: "4,14,24,34,44,54 * * * *"

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
      - name: Check out this repo
        uses: actions/checkout@v3
      - name: Fetch latest data
        run: |-
          curl "https://services9.arcgis.com/RHVPKKiFTONKtxq3/arcgis/rest/services/USA_Wildfires_v1/FeatureServer/0/query?f=json&cacheHint=true&resultOffset=0&resultRecordCount=1000&where=((POOState%20%3D%20%27US-MT%27)%20AND%20(IncidentTypeCategory%20NOT%20IN%20(%27RX%27)))&orderByFields=DailyAcres%20DESC&outFields=*&resultType=standard&returnGeometry=true&spatialRel=esriSpatialRelIntersects" | jq '.'  > dnrc-fires.json
      - name: Commit and push if changed
        run: |-
          git config user.name "Automated"
          git config user.email "actions@users.noreply.github.com"
          git add -A
          timestamp=$(date -u)
          git commit -m "Latest data: ${timestamp}" || exit 0
          git push https://${secrets.ACCESS_TOKEN}@github.com/jolness1/dnrc-history.git
